/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "isaAgentObject.h"
#include <sys/sysinfo.h>
#include <time.h>


static char myLogin[9] = "xwoska00"; // xlogin ktery se vraci při dotazu na objectLogin
static int myInt; // r/w promena ktera se vraci pri dotazu na objectInteger
static int myInt_bak; // zaloha myInt
static char myTime[255]; // buffer na vraceni casu
static char myInfo[22]; // buffer na vraceni info o systemu (v mem pripade pocet jader procesoru)

/** Initializes the isaAgentObject module */
void
init_isaAgentObject(void)
{
    const oid objectLogin_oid[] = { 1,3,6,1,3,22,1 };
    const oid objectTime_oid[] = { 1,3,6,1,3,22,2 };
    const oid objectInteger_oid[] = { 1,3,6,1,3,22,3 };
    const oid objectMyOwn_oid[] = { 1,3,6,1,3,22,4 };

  DEBUGMSGTL(("isaAgentObject", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("objectLogin", handle_objectLogin,
                               objectLogin_oid, OID_LENGTH(objectLogin_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("objectTime", handle_objectTime,
                               objectTime_oid, OID_LENGTH(objectTime_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("objectInteger", handle_objectInteger,
                               objectInteger_oid, OID_LENGTH(objectInteger_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("objectMyOwn", handle_objectMyOwn,
                               objectMyOwn_oid, OID_LENGTH(objectMyOwn_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_objectLogin(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                      myLogin,
                                     sizeof(myLogin)-1);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_objectLogin\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_objectTime(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    time_t timeNow;
    struct tm * timeinfo;
    time(&timeNow);
    timeinfo = localtime(&timeNow);
    // V structu timeInfo mame uchavne data o aktualnim casu
    // Pomoci funkce sprintf data poskaldame do takoveho formatu aby odpovidal predepsanemu
    int length = sprintf(myTime, "%d-%d-%dT%02d:%02d:%02d+01:00", timeinfo->tm_year + 1900, timeinfo->tm_mon + 1, timeinfo->tm_mday, timeinfo->tm_hour, timeinfo->tm_min, timeinfo->tm_sec);
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                      &myTime,
                                     length);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_objectTime\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_objectInteger(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                      &myInt,
                                     sizeof(myInt));
            break;

        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

	case MODE_SET_RESERVE2:

            myInt_bak = myInt;

            break;

        case MODE_SET_FREE:

            break;

        case MODE_SET_ACTION:

            myInt = *(requests->requestvb->val.integer);

            break;

        case MODE_SET_COMMIT:

            break;

        case MODE_SET_UNDO:

             myInt = myInt_bak;

            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_objectInteger\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_objectMyOwn(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    int length = sprintf(myInfo, "Number of cores: %d", get_nprocs_conf());
    switch(reqinfo->mode) {
	
	
        case MODE_GET:

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     			myInfo,
                                     			length);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_objectMyOwn\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
