/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ISAAGENTOBJECT_H
#define ISAAGENTOBJECT_H

/* function declarations */
void init_isaAgentObject(void);
Netsnmp_Node_Handler handle_objectLogin;
Netsnmp_Node_Handler handle_objectTime;
Netsnmp_Node_Handler handle_objectInteger;
Netsnmp_Node_Handler handle_objectMyOwn;

#endif /* ISAAGENTOBJECT_H */
